# Generated by Django 5.2.8 on 2025-11-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaitem',
            name='lugar_item',
            field=models.CharField(choices=[('bar', 'Bar'), ('cocina', 'Cocina')], default='cocina', max_length=100, verbose_name='Proveniencia del Item'),
        ),
    ]
