# Generated by Django 5.2.7 on 2025-11-16 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('comedor', 'Comedor'), ('llevar', 'Para Llevar'), ('delivery', 'Delivery')], default='comedor', max_length=20, verbose_name='Tipo de Pedido'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='comedor.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='comedor.mesa', verbose_name='Mesa'),
        ),
    ]
